version: "1.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
volumes:
  db-data: 